### ISSUE TITLE
Multiple series in same .vsi file -> Annotations placed on wrong image when running for project

### ISSUE THREAD

**Issue by lacan** [qupath/qupath-bioformats-extension#1]
I am trying to run an imageJ macro from a script that makes use of 
`run("Send Overlay to QuPath", "choose_object_type=Annotation");`

When working with VSI files that have a single series, "Run for project" works just fine. The overlay gets sent to the right image in the project

However, if there are multiple series in the same VSI file, then it fails and adds all annotations that are returning from ImageJ to the first series of the image in question. 

Where can I start looking to see how to solve this?

Best
Oli

**Comment by lacan** [comment]
I think I found the issue. Seen here

https://github.com/qupath/qupath/blob/a3e9246640f9819701d57c513bb21a0546cff130/qupath-extension-ij/src/main/java/qupathj/QUPath_Send_Overlay_to_QuPath.java#L90

As the plugin asks for the current viewer, and this one does not change while running on a project, it just keeps putting them onto the same image. 
Though I am surprised it worked before then...

**Comment by petebankhead** [comment]
Maybe this helps: https://github.com/qupath/qupath/issues/136

**Comment by lacan** [comment]
Yup that was it. Merci
