### ISSUE TITLE
Handle WSI images with empty Names

### ISSUE THREAD

**Issue by sbesson** [qupath/qupath-bioformats-extension#10]
While pre-testing Bio-Formats 6 with QuPath, I noticed that the latest version of this extension fails not handle WSI images with empty [name](https://www.openmicroscopy.org/Schemas/Documentation/Generated/OME-2016-06/ome_xsd.html#Image_Name) in the populated OME-XML metadata.

This issue can be reproduced with the following combination of software and data:

- QuPath 0.1.2 and qupath-bioformats-extension 0.0.7
- [Bio-Formats 6.0.0-rc1](https://downloads.openmicroscopy.org/bio-formats/6.0.0-rc1/)
- [Leica-1.scn](https://downloads.openmicroscopy.org/images/Leica-SCN/openslide/Leica-1/Leica-1.scn)

With the above, the macro image opens as expected but the WSI image fails with the following error:

<img width="1359" alt="screen shot 2019-02-13 at 20 55 14" src="https://user-images.githubusercontent.com/1355463/52743333-b00fb300-2fd1-11e9-945f-747238362693.png">

Downgrading the extension to 0.0.5 is sufficient to restore the opening of the file.

**Comment by petebankhead** [comment]
Thanks @sbesson this extension will be retired, and it has been (mostly) rewritten for inclusion in the next release.

I've checked the files and it does open ok with my latest code, however I see the same thing where the name appears to me missing, which causes QuPath more trouble than it should.

If I call
```groovy
OMEXMLMetadata metadata = (OMEXMLMetadata)reader.getMetadataStore();
return metadata.dumpXML();
```
I get the following
```xml
<?xml version="1.0" encoding="UTF-8"?>
<OME xsi:schemaLocation="http://www.openmicroscopy.org/Schemas/OME/2016-06 http://www.openmicroscopy.org/Schemas/OME/2016-06/ome.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.openmicroscopy.org/Schemas/OME/2016-06">
  <Instrument ID="Instrument:0">
    <Objective ID="Objective:0:0" NominalMagnification="0.60833" LensNA="0.7" CalibratedMagnification="0.60833"/>
    <Objective ID="Objective:0:1" NominalMagnification="20.0" LensNA="0.4" CalibratedMagnification="20.0"/>
  </Instrument>
  <Image ID="Image:0" Name="macro">
    <AcquisitionDate>2011-05-31T09:33:14.310</AcquisitionDate>
    <Description>Collection ImageCollection_0000000128</Description>
    <InstrumentRef ID="Instrument:0"/>
    <ObjectiveSettings ID="Objective:0:0"/>
    <Pixels ID="Pixels:0" Type="uint8" SizeZ="1" SizeY="4668" SizeX="1616" SizeT="1" SizeC="3" SignificantBits="8" PhysicalSizeYUnit="µm" PhysicalSizeY="16.438446015424162" PhysicalSizeXUnit="µm" PhysicalSizeX="16.438446163366336" Interleaved="false" DimensionOrder="XYCZT" BigEndian="false">
      <Channel ID="Channel:0:0" SamplesPerPixel="3" IlluminationType="Transmitted">
        <LightPath/>
      </Channel>
      <Plane TheZ="0" TheT="0" TheC="0" PositionYUnit="reference frame" PositionY="0" PositionXUnit="reference frame" PositionX="0"/>
    </Pixels>
  </Image>
  <Image ID="Image:1" Name="">
    <AcquisitionDate>2011-05-31T09:43:06.873</AcquisitionDate>
    <Description>Collection ImageCollection_0000000128</Description>
    <InstrumentRef ID="Instrument:0"/>
    <ObjectiveSettings ID="Objective:0:1"/>
    <Pixels ID="Pixels:1" Type="uint8" SizeZ="1" SizeY="38432" SizeX="36832" SizeT="1" SizeC="3" SignificantBits="8" PhysicalSizeYUnit="µm" PhysicalSizeY="0.5" PhysicalSizeXUnit="µm" PhysicalSizeX="0.5" Interleaved="false" DimensionOrder="XYCZT" BigEndian="false" PhysicalSizeZUnit="µm" PhysicalSizeZ="0.4">
      <Channel ID="Channel:1:0" SamplesPerPixel="3" IlluminationType="Transmitted">
        <LightPath/>
      </Channel>
      <Plane TheZ="0" TheT="0" TheC="0" PositionYUnit="reference frame" PositionY="17548313" PositionXUnit="reference frame" PositionX="5389341"/>
    </Pixels>
  </Image>
</OME>
```
Is it right that the name should be empty?  Somehow QuPath needs to be able to store a reference to the specific image within the file, and until now it has used the name when it probably ought not to.  Is the safest way for me to identify a specific image (consistently, including across versions) to use the series number?

**Comment by petebankhead** [comment]
Sorry, I see you mentioned the empty name several times and I missed it... the name is not empty if I look at the XML in Fiji - is this because of the (un)flattened resolutions?

**Comment by sbesson** [comment]
Hi @petebankhead, yes this logic is specific to the unflattened resolutions API. For instance in 5.9.2, see https://github.com/openmicroscopy/bioformats/blob/9fc607f85b8900be786813296f1eee75cc1ed883/components/formats-gpl/src/loci/formats/in/NDPIReader.java#L491-L499.

This behavior has been in place for some WSI formats like Hamamatsu NDPI and in 6.0.0 more readers have been updated to follow this behavior. In general, the series index is certainly the unambiguous way to map to a specific image within a fileset although for UI purposes, using the series name if not empty is certainly valuable.

/cc @melissalinkert @joshmoore @dgault

**Comment by petebankhead** [comment]
Thanks @sbesson , this is very helpful.

I've seen that the current code is still affected by this and I've made a minor change that means precisely one image with no name can be handled 'properly' (at least without throwing an exception), which would match with the OpenSlide behavior.  But ultimately projects in QuPath need a more thorough revision for multiple reasons.

I need a string that I can represent each image, and the most sensible way I can think to do it is to use a URL, e.g.
```
file://path/to/image.ext?series=0
```
or perhaps
```
file://path/to/image.ext#0
```
Do any of you have any suggestions for the most maintainable way to do this (i.e. incorporating the series number with a query, fragment or some other way)?

This should support images read using Bio-Formats, OpenSlide and ideally also OMERO (although with the protocol suitably changed).  Ideally the representation would be as similar as possible in all cases, but in practice the appropriate reader will be presented with the URL and need to return a response quickly indicating whether or not it is a kind of image that it supports.

(I'd like to include Bio-Formats and OMERO support by default in the next release, but need to maintain compatibility with OpenSlide for the small number of whole slide formats only it supports... most notably .mrxs)

**Comment by sbesson** [comment]
Thanks @petebankhead. Using a string representation to specify a local file using the URI protocol is interesting. The [File URI scheme](https://tools.ietf.org/html/rfc8089) does not provide any mention of the query/fragment components defined in the [generic URI scheme](https://tools.ietf.org/html/rfc3986). My main concern is the construction of something custom or even not compliant.

Do you anticipate you will need to capture more information eventually? It feels like a query structure is the most extensible solution. For instance, the library `Bio-Formats/OpenSlide` could even be captured that way.

**Comment by petebankhead** [comment]
Thanks @sbesson - ah, I hadn't checked out those scheme links. Hmmm...
I've switched to using the URI representation for now, and find it useful. But I share your concerns and wonder if it might be storing up problems for the future... I will proceed with caution and remain open to ideas.

I was thinking that the library would be stored elsewhere and I'd like to resist squeezing more out of the URI.

**Comment by sbesson** [comment]
With QuPath 2.0.2, this issue is now resolved. Closing.

<img width="1264" alt="Screen Shot 2019-03-16 at 08 05 08" src="https://user-images.githubusercontent.com/1355463/54472583-464a1b00-47c2-11e9-8f3d-d04985b117ef.png">

@petebankhead: I assume this repository will eventually be marked as archived and that we should start watching the combination of http://forum.image.sc/tags/qupath and https://github.com/qupath/qupath/issues as the sources of report/feedback?
